In [1]:
import pandas as pd

df = pd.read_csv("../data/googleplaystore_cleaned.csv")
game_df = df[df["Category"] == "GAME"]
print(game_df.head(10))

                         App Category  Rating   Reviews                Size  \
1275                  ROBLOX     GAME     4.5   4447388                 67M
1276          Subway Surfers     GAME     4.5  27722264                 76M
1277        Candy Crush Saga     GAME     4.4  22426677                 74M
1278               Solitaire     GAME     4.7    254258                 23M
1279          Bubble Shooter     GAME     4.5    148897                 46M
1280  Hello Kitty Nail Salon     GAME     4.2    369203                 24M
1281              slither.io     GAME     4.4   5234162  Varies with device
1282            Clash Royale     GAME     4.6  23133508                 97M
1283            Temple Run 2     GAME     4.3   8118609                 62M
1284                     Pou     GAME     4.3  10485308                 24M

        Installs  Type Price Content Rating                        Genres  \
1275   100000000  Free     0   Everyone 10+  Adventure;Action & Adventure
1276  1000000000  Free     0   Everyone 10+                        Arcade
1277   500000000  Free     0       Everyone                        Casual
1278    10000000  Free     0       Everyone                          Card
1279    10000000  Free     0       Everyone                        Casual
1280    50000000  Free     0       Everyone           Casual;Pretend Play
1281   100000000  Free     0       Everyone                        Action
1282   100000000  Free     0   Everyone 10+                      Strategy
1283   500000000  Free     0       Everyone                        Action
1284   500000000  Free     0       Everyone                        Casual

     Last Updated         Current Ver   Android Ver
1275    31-Jul-18        2.347.225742    4.1 and up
1276    12-Jul-18              1.90.0    4.1 and up
1277     5-Jul-18           1.129.0.2    4.1 and up
1278     1-Aug-18             2.137.0    4.1 and up
1279    17-Jul-18              1.20.1  4.0.3 and up
1280    17-Apr-18                 1.5    4.1 and up
1281    14-Nov-17  Varies with device    2.3 and up
1282    27-Jun-18               2.3.2    4.1 and up
1283     5-Jul-18              1.49.1    4.0 and up
1284    25-May-18              1.4.77    4.0 and up

Let's compare FREE vs PAID distribution

In [4]:
#Checking proportion of free and paid games
(game_df["Price"] == "0").mean()
#Result shows that 92% of games are free, which is a common trend in the app marketplace.

np.float64(0.9166666666666666)

In [ ]:
#Comparing performance of free vs paid games
game_df.groupby(game_df["Price"] == "0")["Installs"].describe()
#The results show that free games have a much higher average number of installs
#compared to paid games, which is expected given the large proportion of free games in the market.

,count,mean,std,min,25%,50%,75%,max
Price,,,,,,,,
False,76.0,2.763061e+05,1.170023e+06,1.0,1000.0,10000.0,100000.0,1.000000e+07
True,836.0,1.657627e+07,5.464948e+07,5.0,100000.0,1000000.0,10000000.0,1.000000e+09

In [8]:
#Now we go into sub-category to see which performs best
game_df["Genres"].value_counts().head(15)

Genres
Action          292
Arcade          171
Racing           86
Adventure        71
Card             44
Board            38
Casino           37
Trivia           28
Puzzle           24
Casual           23
Word             22
Music            18
Strategy         17
Role Playing     15
Simulation       10
Name: count, dtype: int64

In [12]:
#Compare median installs for top 5 genres
game_df["Primary_Genre"] = game_df["Genres"].str.split(";").str[0]
genre_summary = game_df.groupby("Primary_Genre")["Installs"].agg(["count", "median", "mean"])
genre_summary.sort_values("median", ascending=False).head(10)

               count      median          mean
Primary_Genre
Sports             6  55000000.0  5.266667e+07
Casual            27  10000000.0  8.551852e+07
Puzzle            24  10000000.0  2.513333e+07
Strategy          17  10000000.0  2.690000e+07
Simulation        12  10000000.0  1.343333e+07
Role Playing      15   5000000.0  7.273333e+06
Word              22   3000000.0  7.689659e+06
Action           295   1000000.0  1.189165e+07
Racing            86   1000000.0  1.628193e+07
Arcade           171   1000000.0  2.195952e+07

We notice that Sports games only have 6 sample but alf of them have more than 5M installs which is very high. This means it's very competitive.
While in top5 are more stable, less risky, very suitable for new startups.

In [13]:
game_df.groupby("Primary_Genre")["Rating"].agg(["count", "median", "mean", "std"]).sort_values("median", ascending=False).head(10)

               count  median      mean       std
Primary_Genre
Puzzle            24    4.60  4.533333  0.180980
Sports             6    4.55  4.533333  0.081650
Casual            27    4.50  4.444444  0.136814
Simulation        12    4.50  4.383333  0.438662
Role Playing      15    4.40  4.406667  0.170992
Casino            37    4.40  4.286486  0.310163
Strategy          17    4.40  4.347059  0.226709
Action           295    4.30  4.246102  0.297455
Adventure         72    4.30  4.183333  0.315782
Word              22    4.30  4.340909  0.315714

After seeing these 2 tables, we can tell that sports games have very high reward but very competitive. While puzzle and casual games follow in ratings but the market sizes are bigger, indicate that a safer choice for startups.